import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const res = await fetch(
		"https://api.themoviedb.org/3/movie/11?api_key=96a0f6de0d8648b87be78503fc99fb76"
	);
	const data = await res.json();
	if (!data) return null;
	return (
		<ClerkProvider>
			<html lang="en" {...data}>
				<body className={inter.className} {...data}>
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
